---
- name: Load seeding vars
  include_vars:
    file: "{{ _ar_os_seed_config_dest_templates }}/seed-hosts.yml"

- name: "Assertions: ar_os_seed (apply)"
  assert:
    that: "{{ ar_os_seed_apply_assertions }}"

- name: Login to OpenShift
  include_role:
    name: ar_os_common
    tasks_from: login
  vars:
    ar_os_common_openshift_login_url: "{{ ar_os_seed_openshift_login_url }}"

- name: Include openshift-applier role
  include_role:
    name: openshift-applier/roles/openshift-applier
