---
- name: "Assertions: ar_os_seed (seed)"
  assert:
    that: "{{ ar_os_seed_content_assertions }}"

- name: Login to OpenShift
  include_role:
    name: ar_os_common
    tasks_from: login
  vars:
    ar_os_common_openshift_login_url: "{{ ar_os_seed_openshift_login_url }}"

- name: Check if Namespace exists
  command: "oc get project {{ ar_os_seed_namespace }}"
  register: project_present
  failed_when: false
  changed_when: false

- set_fact:
    _ar_os_seed_create_namespace: true
  when: project_present.rc != 0

- name: Create seed vars
  template:
    src: seed-hosts-template.yml.j2
    dest: "{{ _ar_os_seed_config_dest_templates }}/seed-hosts.yml"
